all:
	# CMake is a configuration program, sometimes called a "meta" build system. 
	# As with other configuration systems, CMake is not ultimately responsible for running the commands which produce the software build. 
	# Instead, CMake generates a build system based on project, environment, and user-provided configuration information.
	cmake -h -G

