all:
	# CMake is a configuration program, sometimes called a "meta" build system. 
	# As with other configuration systems, CMake is not ultimately responsible for running the commands which produce the software build. 
	# Instead, CMake generates a build system based on project, environment, and user-provided configuration information.
	# https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html
	cmake -h -G
	# In https://github.com/ontouchstart/rabbit-holes/actions/workflows/windows-2025.yml?query=branch%3Acmake
	# The default generator will be
	# * Visual Studio 17 2022        = Generates Visual Studio 2022 project files.

