services:
  bash:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./home:/home
      - ./home/.pi:/root/.pi
      - ./home/github:/github
    command: bash

  pi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./home/.pi:/root/.pi
      - ./home/pi:/home
      - ./home/github:/github

  claude:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./home/claude:/home
      - ./home/github:/github

  codex:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./home/codex:/home
      - ./home/.codex:/root/.codex
      - ./home/github:/github
