services:
  bash:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./home:/home
      - ./home/.pi:/root/.pi
    command: bash

  pi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./home/.pi:/root/.pi
      - ./home/pi:/home

  claude:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./home/claude:/home
