all:
	echo "This Makefile should be run outside of docker container"
	cat -n Makefile
.pi:
	git clone git@github.com:ontouchstart/.pi.git

codex:
	git clone https://github.com/openai/codex.git

deno:
	git clone https://github.com/denoland/deno.git

ggml:
	git clone https://github.com/ggml-org/ggml.git

llama.cpp:
	git clone https://github.com/ggml-org/llama.cpp.git

openai-node:
	git clone https://github.com/openai/openai-node.git

pi-mono:
	git clone https://github.com/badlogic/pi-mono.git
	-cd pi-mono && npm install && npm run build && npm test

