//! # A Gentle Introduction to TeX
//! 
//! [Plan](https://gist.github.com/ontouchstart/80647f418f561c2cb6d9a581fc15c3db) generated by 
//! [unsloth/gpt-oss-20b-GGUF](https://github.com/ontouchstart/rabbit-holes/tree/main/llama-cpp/models/unsloth/gpt-oss-20b-GGUF)
//!
//! [gentle.pdf](gentle.pdf)
//! ```makefile
#! [doc = include_str!("Makefile")]
//! ```
//!
//! `/Library/TeX/Documentation/texmf-dist-doc/plain/gentle/gentle.tex`
//! ```tex
#! [doc = include_str!("gentle/gentle.tex")]
//! ```
//!
