all:

log-p-git2-rs:
	git -C ../../git2-rs log -p

log-p-libgit2:
	git -C ../../git2-rs/libgit2-sys/libgit2 log -p

log-reverse-p-git2-rs:
	git -C ../../git2-rs log --reverse -p

log-reverse-p-libgit2:
	git -C ../../git2-rs/libgit2-sys/libgit2 log --reverse -p

