Makefile.tex: ../../../../generators/UNIX/add_excutable/Makefile
	echo '\\begin{verbatim}' > Makefile.tex
	cat -n ../../../../generators/UNIX/add_excutable/Makefile >> Makefile.tex
	echo '\\end{verbatim}' >> Makefile.tex
