\begin{verbatim}
     1	all:
     2		# https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html
     3		# We set it to 3.31, which is the lowest on in all three CI environments
     4		# https://cmake.org/cmake/help/latest/command/project.html
     5		# https://cmake.org/cmake/help/latest/command/add_library.html
     6		cmake --version
     7		cat -n CMakeLists.txt
     8		cat -n include/42.h
     9		cat -n include/answer.h
    10		cat -n lib/answer.cc
    11		rm -rf build
    12		cmake -G "Unix Makefiles" -B build
    13		find build | cat -n 
    14		cat -n build/Makefile
    15		make -C build
    16		find build | cat -n 
\end{verbatim}
