Makefile.tex: ../../../../generators/UNIX/add_library/Makefile
	echo '\\begin{verbatim}' > Makefile.tex
	cat -n ../../../../generators/UNIX/add_library/Makefile >> Makefile.tex
	echo '\\end{verbatim}' >> Makefile.tex
