RUSTDOC = rustdoc --edition 2024 -o ../docs
all:
	$(RUSTDOC) playground-uname.rs
	$(RUSTDOC) playground-cat-security_notice.rs
	$(RUSTDOC) playground-read-security_notice.rs
	$(RUSTDOC) playground-free-h.rs
	$(RUSTDOC) playground-rev-pipe.rs
