Makefile.tex: ../../../../generators/UNIX/target_link_libraries/Makefile
	echo '\\begin{verbatim}' > Makefile.tex
	cat -n ../../../../generators/UNIX/target_link_libraries/Makefile >> Makefile.tex
	echo '\\end{verbatim}' >> Makefile.tex
